"""konsol#305 B25: the committed close SPA bundle in konsol/public/close.

The bundle is generated by `close-ui`'s `yarn build` and committed, mirroring
`konsol/public/konsol_exec/` (`git ls-files` there lists index.html, the js,
the css and two woff2 files). These tests read the committed output only —
they never run vite — so they catch a bundle that was never built, a stale
bundle left over from an earlier source tree, and a leftover reference to the
old konsol-exec SPA.
"""
import glob
import hashlib
import json
import os

APP_DIR = os.path.join(os.path.dirname(__file__), "..")
BUNDLE_DIR = os.path.abspath(os.path.join(APP_DIR, "public", "close"))
CLOSE_UI_SRC = os.path.abspath(os.path.join(APP_DIR, "..", "close-ui", "src"))


def _read(path):
    with open(path, "rb") as f:
        return f.read()


def _hash_src_dir(src_dir):
    """Same algorithm as close-ui/vite.config.js's `hashSrcDir`: a sha256
    over every file under src_dir, sorted by relative (posix) path, each
    entry framed as `<relpath>\\0<content>\\0`. The two implementations
    must stay byte-for-byte identical or every build looks stale."""
    files = []
    for root, _dirs, names in os.walk(src_dir):
        for name in names:
            files.append(os.path.join(root, name))
    files.sort()
    h = hashlib.sha256()
    for path in files:
        rel = os.path.relpath(path, src_dir).replace(os.sep, "/")
        h.update(rel.encode("utf-8"))
        h.update(b"\x00")
        h.update(_read(path))
        h.update(b"\x00")
    return h.hexdigest()


def test_close_js_and_css_exist():
    assert os.path.isfile(os.path.join(BUNDLE_DIR, "close.js")), (
        "konsol/public/close/close.js is missing — build it with "
        "`cd close-ui && yarn build` and commit the result."
    )
    assert os.path.isfile(os.path.join(BUNDLE_DIR, "close.css"))


def test_index_html_references_close_js_and_css():
    html = _read(os.path.join(BUNDLE_DIR, "index.html")).decode("utf-8")
    assert "/assets/konsol/close/close.js" in html
    assert "/assets/konsol/close/close.css" in html


def test_no_bundle_file_mentions_the_old_konsol_exec_spa():
    for path in glob.glob(os.path.join(BUNDLE_DIR, "*")):
        if not os.path.isfile(path):
            continue
        content = _read(path)
        assert b"konsol_exec" not in content, path
        assert b"/konsol-exec" not in content, path


def test_signoff_api_sign_was_built_in():
    # B23 wires signoff_api.sign into the sign-off screen. Vite code-splits
    # the SPA by route, so this string lands in whichever emitted *.js chunk
    # holds the sign-off screen (close.SignOff.js as of B23/B25), not
    # necessarily the close.js entry file — so every emitted JS file is
    # searched. A build made before B23 (or any stale bundle missing it)
    # fails this.
    found = any(
        b"konsol.close.signoff_api.sign" in _read(path)
        for path in glob.glob(os.path.join(BUNDLE_DIR, "*.js"))
    )
    assert found, (
        "No file in konsol/public/close/*.js contains "
        "'konsol.close.signoff_api.sign' — the bundle is stale or was built "
        "before B23. Rebuild with `cd close-ui && yarn build`."
    )


def test_bundle_matches_current_close_ui_src():
    # The committed bundle must be reproducible from the committed source.
    # close-ui/vite.config.js's sourceManifestPlugin writes build-manifest.json
    # with a content hash of close-ui/src at build time; this recomputes that
    # same hash from the checked-out tree and compares. A source change with
    # no matching rebuild fails here instead of shipping unnoticed.
    manifest_path = os.path.join(BUNDLE_DIR, "build-manifest.json")
    assert os.path.isfile(manifest_path), (
        "konsol/public/close/build-manifest.json is missing — build with "
        "`cd close-ui && yarn build` (written by vite.config.js's "
        "sourceManifestPlugin) and commit the result."
    )
    with open(manifest_path) as f:
        manifest = json.load(f)
    recorded = manifest.get("srcHash")
    assert recorded, "build-manifest.json has no srcHash"
    current = _hash_src_dir(CLOSE_UI_SRC)
    assert recorded == current, (
        "konsol/public/close is stale: build-manifest.json's srcHash does not "
        "match the current close-ui/src tree. Run `cd close-ui && yarn build` "
        "and commit the refreshed bundle."
    )
