"""konsol#305 B25: the committed close SPA bundle in konsol/public/close.

The bundle is generated by `close-ui`'s `yarn build` and committed, mirroring
`konsol/public/konsol_exec/` (`git ls-files` there lists index.html, the js,
the css and two woff2 files). These tests read the committed output only —
they never run vite — so they catch a bundle that was never built, a stale
bundle left over from an earlier source tree, and a leftover reference to the
old konsol-exec SPA.
"""
import glob
import hashlib
import json
import os
import re

APP_DIR = os.path.join(os.path.dirname(__file__), "..")
BUNDLE_DIR = os.path.abspath(os.path.join(APP_DIR, "public", "close"))
CLOSE_UI_SRC = os.path.abspath(os.path.join(APP_DIR, "..", "close-ui", "src"))


def _read(path):
    with open(path, "rb") as f:
        return f.read()


def _hash_src_dir(src_dir):
    """Same algorithm as close-ui/vite.config.js's `hashSrcDir`: a sha256
    over every file under src_dir, sorted by relative (posix) path, each
    entry framed as `<relpath>\\0<content>\\0`. The two implementations
    must stay byte-for-byte identical or every build looks stale."""
    files = []
    for root, _dirs, names in os.walk(src_dir):
        for name in names:
            files.append(os.path.join(root, name))
    files.sort()
    h = hashlib.sha256()
    for path in files:
        rel = os.path.relpath(path, src_dir).replace(os.sep, "/")
        h.update(rel.encode("utf-8"))
        h.update(b"\x00")
        h.update(_read(path))
        h.update(b"\x00")
    return h.hexdigest()


def _manifest():
    path = os.path.join(BUNDLE_DIR, "build-manifest.json")
    assert os.path.isfile(path), (
        "konsol/public/close/build-manifest.json is missing — build with "
        "`cd close-ui && yarn build` and commit the result."
    )
    with open(path) as f:
        return json.load(f)


#: A relative ES import in the minified bundle: `from"./x.js"`,
#: `import"./x.js"` or `import("./x.js")`.
_REL_IMPORT = re.compile(r"""(?:\bfrom|\bimport)\s*\(?\s*["']\./([^"']+\.js)["']""")


def _relative_imports(path):
    return set(_REL_IMPORT.findall(_read(path).decode("utf-8")))


def test_manifest_names_a_content_hashed_entry_and_stylesheet_that_exist():
    # konsol#305 B26: the entry is content-hashed (close.<hash>.js) so the
    # page needs no `?v=` query. A query makes the page's URL differ from the
    # `./close.js` the lazy chunks import, and the browser then runs the
    # module twice (C1 run 1: a blank period screen).
    manifest = _manifest()
    entry = manifest.get("entry")
    css = manifest.get("css")
    assert entry and re.fullmatch(r"close\.[A-Za-z0-9_-]+\.js", entry), (
        "build-manifest.json must name the content-hashed entry "
        "(close.<hash>.js); got %r" % (entry,)
    )
    assert css and re.fullmatch(r"close\.[A-Za-z0-9_-]+\.css", css), (
        "build-manifest.json must name the content-hashed entry stylesheet "
        "(close.<hash>.css); got %r" % (css,)
    )
    assert os.path.isfile(os.path.join(BUNDLE_DIR, entry)), entry
    assert os.path.isfile(os.path.join(BUNDLE_DIR, css)), css


def test_no_fixed_name_entry_is_left_in_the_bundle():
    # A leftover close.js / close.css is a second copy of the app a stale
    # template or chunk could still load.
    for name in ("close.js", "close.css"):
        assert not os.path.exists(os.path.join(BUNDLE_DIR, name)), name


def test_index_html_references_the_manifest_entry_and_stylesheet():
    manifest = _manifest()
    html = _read(os.path.join(BUNDLE_DIR, "index.html")).decode("utf-8")
    assert '"/assets/konsol/close/%s"' % manifest["entry"] in html
    assert '"/assets/konsol/close/%s"' % manifest["css"] in html


def test_every_relative_import_in_the_bundle_resolves_to_a_bundle_file():
    for path in glob.glob(os.path.join(BUNDLE_DIR, "*.js")):
        for target in _relative_imports(path):
            assert os.path.isfile(os.path.join(BUNDLE_DIR, target)), (
                "%s imports ./%s, which is not in the bundle"
                % (os.path.basename(path), target)
            )


def test_every_chunk_that_imports_the_entry_imports_the_manifest_name():
    # The page loads /assets/konsol/close/<entry>; a chunk resolves
    # `./<entry>` against the same directory, so the URLs are identical and
    # the browser runs the module ONCE. A chunk importing any other
    # close.*.js that is not itself a chunk would start a second instance.
    manifest = _manifest()
    entry = manifest["entry"]
    route_chunks = _relative_imports(os.path.join(BUNDLE_DIR, entry))
    assert route_chunks, "the entry lazily imports no route chunk"
    importers = 0
    for path in glob.glob(os.path.join(BUNDLE_DIR, "*.js")):
        name = os.path.basename(path)
        if name == entry:
            continue
        imports = _relative_imports(path)
        assert "close.js" not in imports, (
            "%s imports ./close.js, not the entry ./%s" % (name, entry)
        )
        if entry in imports:
            importers += 1
    for chunk in route_chunks:
        assert entry in _relative_imports(os.path.join(BUNDLE_DIR, chunk)), (
            "route chunk %s does not import the entry ./%s" % (chunk, entry)
        )
    assert importers >= len(route_chunks)


def test_no_bundle_file_mentions_the_old_konsol_exec_spa():
    for path in glob.glob(os.path.join(BUNDLE_DIR, "*")):
        if not os.path.isfile(path):
            continue
        content = _read(path)
        assert b"konsol_exec" not in content, path
        assert b"/konsol-exec" not in content, path


def test_signoff_api_sign_was_built_in():
    # B23 wires signoff_api.sign into the sign-off screen. Vite code-splits
    # the SPA by route, so this string lands in whichever emitted *.js chunk
    # holds the sign-off screen (close.SignOff.js as of B23/B25), not
    # necessarily the close.js entry file — so every emitted JS file is
    # searched. A build made before B23 (or any stale bundle missing it)
    # fails this.
    found = any(
        b"konsol.close.signoff_api.sign" in _read(path)
        for path in glob.glob(os.path.join(BUNDLE_DIR, "*.js"))
    )
    assert found, (
        "No file in konsol/public/close/*.js contains "
        "'konsol.close.signoff_api.sign' — the bundle is stale or was built "
        "before B23. Rebuild with `cd close-ui && yarn build`."
    )


def test_bundle_matches_current_close_ui_src():
    # The committed bundle must be reproducible from the committed source.
    # close-ui/vite.config.js's sourceManifestPlugin writes build-manifest.json
    # with a content hash of close-ui/src at build time; this recomputes that
    # same hash from the checked-out tree and compares. A source change with
    # no matching rebuild fails here instead of shipping unnoticed.
    manifest_path = os.path.join(BUNDLE_DIR, "build-manifest.json")
    assert os.path.isfile(manifest_path), (
        "konsol/public/close/build-manifest.json is missing — build with "
        "`cd close-ui && yarn build` (written by vite.config.js's "
        "sourceManifestPlugin) and commit the result."
    )
    with open(manifest_path) as f:
        manifest = json.load(f)
    recorded = manifest.get("srcHash")
    assert recorded, "build-manifest.json has no srcHash"
    current = _hash_src_dir(CLOSE_UI_SRC)
    assert recorded == current, (
        "konsol/public/close is stale: build-manifest.json's srcHash does not "
        "match the current close-ui/src tree. Run `cd close-ui && yarn build` "
        "and commit the refreshed bundle."
    )
